//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelerPortal.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Album
    {
        public Album()
        {
            this.AlbumImages = new HashSet<AlbumImage>();
        }
    
        public long Id { get; set; }
        public string Name { get; set; }
        public string CoverPath { get; set; }
        public string ExternalId { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<AlbumImage> AlbumImages { get; set; }
    }
}
