//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelerPortal.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Travel
    {
        public Travel()
        {
            this.Events = new HashSet<Event>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string BriefDescriptionPath { get; set; }
        public string DetailedDescriptionPath { get; set; }
        public System.DateTime Created { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<Event> Events { get; set; }
    }
}
