//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelerPortal.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Comments = new HashSet<Comment>();
        }
    
        public int Id { get; set; }
        public string FBId { get; set; }
        public string VKId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Thumbnail { get; set; }
        public System.DateTime Created { get; set; }
    
        public virtual ICollection<Comment> Comments { get; set; }
    }
}
